### PR TITLE
adding New Braunfels KBAZ

### PR DESCRIPTION
**Pull request by kylehodgson**

### CODE REVIEW

**Comment by ip2location** [comment]
Hi @kylehodgson,

We appreciated this PR, however it seems like you had accidentally removed the header row. Can you please add it back before we can accept this PR?

**Comment by kylehodgson** [comment]
> Hi @kylehodgson,
> 
> We appreciated this PR, however it seems like you had accidentally removed the header row. Can you please add it back before we can accept this PR?

Apologies! Solved. Also added some new airports.

**Comment by ip2location** [comment]
Hi @kylehodgson,

Thanks for the update. However, we noticed that you have inserted wrong region name for one of the new record, which is the following:

```csv
"NZ","Fernside","","NZRT","Rangiora Airfield WMS","-43.2892","172.5413"
```

As a reminder, our `region_name` column is based on the region name from the ISO3166-2. You will have to re-update this record with the correct region name. For a quick reference, Wikipedia had a list for this purpose: https://en.wikipedia.org/wiki/ISO_3166-2:NZ

**Comment by kylehodgson** [comment]
OK, that's been resolved.

**Comment by kylehodgson** [comment]
added another airport (sorry!)

**Comment by ip2location** [comment]
Hi @kylehodgson,

Thanks for the update. The new updates look good now, we will merge the PR now.

**Pull request merged**
