### PR TITLE
Added 176 missing airports, 8 region corrections, 1 IATA code update

### PR DESCRIPTION
**Pull request by Simon-van-Diepen**
Analysing data from flightsfrom.com, I identified 176 missing airports, mostly in Greenland, Russia and China. These have been added. 

Other fixes:
- Tulum, MX has two airports that were mixed up
- 6 airports in Shanxi, CN were labeled as Shaanxi
- ENY name update
- KVD code update to GNJ
- Added regions to JEK, TAS
- Removed space after Teuge Airport, NL

### CODE REVIEW

**Comment by ip2location** [comment]
Hi @Simon-van-Diepen,

Thanks for the contribution. We had reviewed your commits, and found that you have missed out the ICAO code for quite a number of airports. For example:

- `"MX","Quintana Roo","TQO","","Tulum Felipe Carrillo Puerto Airport","20.1661","-87.6592"` had ICAO code MMTL according to https://en.wikipedia.org/wiki/Tulum_International_Airport
- `"AO","Bengo","NBJ","","Luanda Dr. Antonio Agostinho Neto Angola International Airport","-9.0491","13.5000"` had ICAO code FNBJ according to the https://en.wikipedia.org/wiki/Dr._Antonio_Agostinho_Neto_International_Airport.

There are more airports that you might left out their ICAO code with, can you please update your commit to fix this issue before we can merge this PR?

**Comment by Simon-van-Diepen** [comment]
HI @ip2location , I identified an ICAO code for 54 of these airports. I have added them.

**Comment by ip2location** [comment]
Hi @Simon-van-Diepen,

Thanks for the effort. We have go through the updates, and found two issues here:

- For this record '"UZ","Qoraqalpog'iston Respublikasi","MOK","UNTM","Muynaq Airport","43.7574","59.0294"', the correct ICAO code should be "UTNM" according to https://en.wikipedia.org/wiki/Muynak_Airport.
- For this record '"MX","Quintana Roo","TQO","MMTU","Tulum Felipe Carrillo Puerto Airport","20.1661","-87.6592"', the ICAO code should be "MMTL".

Can you please review the findings and update again?

**Comment by Simon-van-Diepen** [comment]
Hi @ip2location 
- For Muynaq Airport you are correct, this was a typo. Thanks for catching it.
- For Tulum airport it appears their own website is inconsistent with the other websites, listing TQO/MMTU. MMTU is the ICAO code of TUY (the other Tulum airport / naval base), MMTL is indeed TQO. 
I have updated both accordingly.

**Comment by ip2location** [comment]
Hi @Simon-van-Diepen,

Thanks for the updates, we will merge it now. :)

**Pull request merged**
