### PR TITLE
Adding EDAY Strausberg

### PR DESCRIPTION
**Pull request by kylehodgson**

### CODE REVIEW

**Comment by kylehodgson** [comment]
Adding EDAY Strausberg, Alpnach LSMA, NZFF Forest FIeld, Beynes and Kagiswil

**Comment by ip2location** [comment]
Hi @kylehodgson,

Thanks for the PR. We had reviewed the changes you made, there is only one thing:

For `"DE","Brandenburg","QPK","EDAY","Strausberg","52.5799","13.9156"`, how did you get the IATA code for the airport? Because we didn't found it in Wikipedia (https://en.wikipedia.org/wiki/List_of_airports_by_ICAO_code:_E#ED_%E2%80%93_Civilian_airports). Once we clarify this, we will merge this PR later.

**Comment by kylehodgson** [comment]
> how did you get the IATA code for the airport?

I found it on Skybrary: https://skybrary.aero/airports/eday.

However, I'm unable to corroborate it anywhere, so I'll remove the IATA code.

**Comment by kylehodgson** [comment]
sorry, didn't mean to add those new airports in on top of this older PR will try to be more precise in future

**Comment by ip2location** [comment]
Hi @kylehodgson,

Thanks for the efforts. We will merge it now.

**Pull request merged**
