### PR TITLE
add airports: ADB, DME, ZDM, XNH, PKX, ZGN, WHU, GIG, GRU, ITJ, VCP, CNF

### PR DESCRIPTION
**Pull request by jhard**
I used this list to map Cloudflare datacenters and found a few airports that were not yet included.
I did not manage to locate an ICAO code for all of them, so some are left empty.

Since I'm not sure what sorting criteria is used, I have added the airports to the bottom of the block of the country in question.

### CODE REVIEW

**Comment by ip2location** [comment]
Hi jhard,

Thanks for the PR. However, we cannot accept the PR now because you records contains few issues:

1. Our records is sorted by country code first and region name then, so please add the record accordingly.
2. Our second column is region name, which is following the ISO3166-2 standard. I found that some of your records are filling the city name instead, can you please rectify following our ISO3166-2 list?(https://www.ip2location.com/free/iso3166-2)

**Comment by jhard** [comment]
@ip2location I'll happily change to the ISO3166-2 region names, I wasn't aware that's what was used.

For the sorting, I don't think I understand. The first lines in the file are currently
```
"AE","Ash Shariqah","SHJ","OMSJ","Sharjah International Airport","25.3286","55.5172"
"AE","Abu Zaby","AZI","OMAD","Al Bateen Executive Airport","24.4283","54.4581"
"AE","Al Fujayrah","FJR","OMFJ","Fujairah International Airport","25.1122","56.324"
"AE","Abu Zaby","XSB","OMBY","Sir Bani Yas Airport","24.2836","52.5803"
"AE","Ra's al Khaymah","RKT","OMRK","Ras Al Khaimah International Airport","25.6135","55.9388"
"AE","Dubayy","DWC","OMDW","Al Maktoum International Airport","24.8964","55.1614"
"AE","Abu Zaby","DHF","OMAM","Al Dhafra Air Base","24.2482","54.5477"
```
which are not sorted by any criteria other than the country code as far as I can tell.
Do you want me to sort the whole file?

**Comment by ip2location** [comment]
Hi @jhard ,

In that case, let's forget about the sorting. You can update the second column first.

**Comment by stephen-soltesz** [comment]
@jhard will you be able to complete this PR? We would welcome other addition of GIG & GRU and others to the dataset - we can open a separate PR if that would be more helpful

**Comment by ip2location** [comment]
Hi @jhard,

We are cleaning out stalled PR, since it had been inactive for almost one year, we will close this PR first. Please open a new PR if you have made the update and would like to submit again.

**Pull request closed without merging**
